---

- hosts: Infra
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 state=latest
      when: ansible_os_family == "Debian"

    - name: install httpd
      yum: name=httpd state=latest
      when: ansible_os_family == "RedHat"