---
- hosts: Infra
  become: yes
  tasks:
    - name: install stuff
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
         - vim
         - name
         - apache2

---
- hosts: Infra
  become: yes
  tasks:
    - name: show contents
      debug: msg={{item}}
      with_file:
         - file1.txt
         - file2.txt


---
- hosts: Infra
  become: yes
  tasks:
    - name: print sequence
      debug: msg={{item}}
      with_sequence: star=1 end=10